---
- name: create users
  hosts: all
  become: yes
  vars_files:
    - user_list.yml
  tasks:
    - name: create group
      group:
        name: "{{ item.group }}"
        state: present

    - name: create user
      user:
        name: "{{ item.user }}"
        state: present
...
