---
- name: create users
  hosts: all
  become: yes
  vars_files: user_list.yml
  tasks:
    - name: create group
      group:
        name: "{{ item.group }}"
        state: present
      with_items: "{{ users }}"
    - name: add users
      user:
        name: "{{ item.name }}"
        group: "{{ item.group }}"
        state: present
      with_items: "{{ users }}"
