---
- name: create users
  hosts: all
  become: yes
  vars_files:
    - user_list.yml
  tasks:
    - name: Group create
      group:
        name: "{{ item.group }}"
        state: present
      with_items: "{{ users }}"

    - name: user creation
      user:
        name: "{{ item.name }}"
        group: "{{ item.group }}"
        state: present
      with_items: "{{ users }}"
...
